### ISSUE TITLE
Normalize problem

### ISSUE THREAD

**Issue by pangxiao2013** [giddyyupp/ganilla#11]

**Comment by pangxiao2013** [comment]
In base_dataset.py file,  I see "    transform_list += [transforms.ToTensor(),
                       transforms.Normalize((0.5, 0.5, 0.5),
                                            (0.5, 0.5, 0.5))]"
is that right? How can you get the mean  or std.

**Comment by giddyyupp** [comment]
yes, that's right. Normalization values are taken from the CycleGan repo and since we are using the same natural images, we didn't change them.
