### ISSUE TITLE
I don't know why the models/networks.py  include the UnetGenator part

### ISSUE THREAD

**Issue by Flyooofly** [giddyyupp/ganilla#13]
Thank you~ I can't understand why the models/networks.py  include the UnetGenator part.I don't find any where that you have used that.

**Comment by giddyyupp** [comment]
Hi, its just there if you want to train pix2pix or cyclegan with unet backbone. yes it is not used in ganilla.

**Comment by Flyooofly** [comment]
> Hi, its just there if you want to train pix2pix or cyclegan with unet backbone. yes it is not used in ganilla.

OK,Thank you~
