### ISSUE TITLE
About the performance of using the usnet_128 or usnet_256 to the cyclegan backbone

### ISSUE THREAD

**Issue by Flyooofly** [giddyyupp/ganilla#14]
Hi, I have try the results that using the usnet as the backbone of the cyclegan  for training our dataset. And I find the results are better than the res_net18 or 34. When I use the resnet ,the results include many artifacts. So I‘m curious that how the results the unet as the backbone for your dataset  and why you last choose the resnet. Thank you, I'm sorry my English is not good.

**Comment by giddyyupp** [comment]
Hi,
in our case unet backbone performed worse than resnet18 and resnet_9blocks. However, performances of these backbones vary between datasets. So its normal actually :)

**Comment by Flyooofly** [comment]
> Hi,
> in our case unet backbone performed worse than resnet18 and resnet_9blocks. However, performances of these backbones vary between datasets. So its normal actually :)

OK,Thank you!
