### ISSUE TITLE
Bad results using the pre-trained "Miyazaki"

### ISSUE THREAD

**Issue by LorenzoPanico** [giddyyupp/ganilla#2]
Hello, i have tried the pre-trained "Miyazaki" model on colab without good result (using 1 pic, the result is a looks just a little filtered)

`!python /content/drive/My\ Drive/ganilla/test.py --dataset_mode single --resize_or_crop none  --dataroot /content/in1 --name /content/drive/My\ Drive/Miyazaki/ --model test --results_dir /content/`

output: 

`----------------- Options ---------------
             aspect_ratio: 1.0                           
               batch_size: 1                             
          checkpoints_dir: /media/test/Samhi/GANILLA/fpn-gan/checkpoints/GANILLA
         cityscape_fnames: /media/test/Samhi/GANILLA/fpn-gan/dataset/cityscape_evaluate/f_names.txt
               cityscapes: False                         
                 dataroot: /content/in1                  	[default: /media/test/Samhi/GANILLA/fpn-gan/dataset/photo2axel/]
             dataset_mode: single                        
                direction: AtoB                          
          display_winsize: 256                           
                    epoch: 100                           
                     eval: False                         
                 fineSize: 256                           
              fpn_weights: [1.0, 1.0, 1.0, 1.0]          
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: normal                        
                 input_nc: 3                             
                  isTrain: False                         	[default: None]
                 loadSize: 256                           
         max_dataset_size: inf                           
                    model: test                          
             model_suffix:                               
               n_layers_D: 3                             
                     name: /content/drive/My Drive/Miyazaki/	[default: photo2korky_ganilla_dropout]
                      ndf: 64                            
                     netD: basic                         
                     netG: resnet_fpn                    
                      ngf: 64                            
               no_dropout: True                          
                  no_flip: False                         
                     norm: instance                      
                    ntest: inf                           
                 num_test: 751                           
              num_threads: 8                             
                output_nc: 3                             
                    phase: test                          
           resize_or_crop: none                          	[default: resize_and_crop]
              results_dir: /content/                     	[default: ./results/]
           serial_batches: False                         
                   suffix:                               
                  verbose: False                         
----------------- End -------------------
dataset [SingleImageDataset] was created
initialize network with normal
model [TestModel] was created
loading the model from /content/drive/My Drive/Miyazaki/100_net_G.pth
---------- Networks initialized -------------
[Network G] Total number of parameters : 7.228 M
-----------------------------------------------
creating web directory /content/drive/My Drive/Miyazaki/test_100
processing (0000)-th image... ['/content/in1/vlcsnap.png']`

**Comment by zxq2233** [comment]
https://colab.research.google.com/drive/1Kwf09IOBDPY6n0s42topuNokZWQ4tLc-
