### ISSUE TITLE
Non-relative file paths in options

### ISSUE THREAD

**Issue by Fraser-Paine** [giddyyupp/ganilla#4]
All of the options files are written with non-relative file paths which makes the recommended run commands in the README fail.

e.g.   --checkpoints_dir 

default value is:   "/media/test/Samhi/GANILLA/fpn-gan/checkpoints/GANILLA"

Also this project works perfectly fine on Windows with no adjustments at all, the only issue was the data fetching .sh scripts, but manually downloading the monet2photo data set is very easy.

**Comment by giddyyupp** [comment]
thanks for informing about that, I will fix it asap. and also clarification about windows, will add that to the ReadMe.
