### ISSUE TITLE
--epoch default set to '100' instead of 'latest'

### ISSUE THREAD

**Issue by Robotuks** [giddyyupp/ganilla#6]
Hey, 

I was trying to continue training from epoch 40 with options `--continue_train --epoch_count 40` and it was a bit weird as it tried to load epoch 100 which did't exist atm :D. After a bit of investigation found that --epoch option is  '100' on default although in CycleGAN project it is set to 'latest'. 
This is unclear as this also not mentioned in FAQ

**Comment by giddyyupp** [comment]
hello, thank you for informing about that, I added this information to qa.md.
