### ISSUE TITLE
Where is GANILLA located..?

### ISSUE THREAD

**Issue by zwep** [giddyyupp/ganilla#7]
Hi! 

I was wondering where the implementation of your model is. Since in your code I only see the implementation of pix2pix or cyclegan. Do I miss something..? Or have you done something special in your implementation?

**Comment by giddyyupp** [comment]
Hello,
it is in the models/networks.py file. you can check the line 89 for the definition, and 406 and afterward for network details.

**Comment by zwep** [comment]
Ah thanks, sorry for the trivial question. I just expected that it would have an implementation similar to the pix2pix and cyclegan model in your repo.

**Comment by giddyyupp** [comment]
no problem, since the training is similar for cyclegan and ganilla network could be used in both cyclegan and pix2pix training schemes, I just added to network definitions.
