### ISSUE TITLE
How to get the dataset used for training ganilla?  could you plz tell me more specifically？

### ISSUE THREAD

**Issue by gzhhhere** [giddyyupp/ganilla#8]

**Comment by gzhhhere** [comment]
“No module named scraper_openlibrary”...  could you please help me  get the dataset..  QAQ

**Comment by giddyyupp** [comment]
hello, its in the datasets folder. Readme about how to download is in the docs/datasets.md

**Comment by scutlrr** [comment]
python openlibraryImageDownloaderMain.py --openlib_username <username> --openlib_password <pass>

Do I still need to apply for an account?

**Comment by giddyyupp** [comment]
I am closing this issue now, if you have further questions please re-open.
